#define DRAGON_STRENGTH 70
#define DRAGON_AGILITY 50
#define DRAGON_INTELLIGENCE 30

#define GIANT_STRENGTH 85
#define GIANT_AGILITY 30
#define GIANT_INTELLIGENCE 35

#define ARCHER_STRENGTH 35
#define ARCHER_AGILITY 75
#define ARCHER_INTELLIGENCE 40

#define GOBLIN_STRENGTH 50
#define GOBLIN_AGILITY 90
#define GOBLIN_INTELLIGENCE 10

#define WITCH_STRENGTH 40
#define WITCH_AGILITY 30
#define WITCH_INTELLIGENCE 80

#define GHOST_STRENGTH 40
#define GHOST_AGILITY 40
#define GHOST_INTELLIGENCE 70

